import { Product } from "./types";

const MOCK_CREATED_AT = "2026-01-01T08:00:00.000Z";

export const mockProducts: Product[] = [
  {
    id: 9001,
    name: "Sokoline Utility Backpack",
    slug: "sokoline-utility-backpack",
    description:
      "A durable everyday backpack designed for campus routines, with compartments for books, laptops, and accessories.",
    price: "79.99",
    discount_price: "59.99",
    is_on_sale: true,
    stock: 42,
    shop: 101,
    shop_name: "Alpha Studio",
    shop_slug: "alpha-studio",
    category: { id: 1, name: "Accessories", slug: "accessories" },
    tags: [],
    images: [
      { id: 1, image: "/hero-image.jpg", alt_text: "Backpack hero", is_feature: true },
      { id: 2, image: "/about-section-image.jpg", alt_text: "Backpack detail", is_feature: false },
    ],
    variants: [
      {
        id: 9101,
        name: "Standard",
        color_name: "Graphite",
        color_hex: "#3F3F46",
        size: "M",
        price_override: null,
        stock: 20,
        image: 1,
        image_url: null,
      },
      {
        id: 9102,
        name: "Standard",
        color_name: "Indigo",
        color_hex: "#4338CA",
        size: "M",
        price_override: null,
        stock: 22,
        image: 2,
        image_url: null,
      },
    ],
    shipping_info: "Ships within 1–2 business days.",
    return_policy: "Returns accepted within 14 days.",
    has_free_shipping: true,
    has_free_returns: true,
    is_safety_certified: true,
    average_rating: 4.7,
    review_count: 36,
    created_at: MOCK_CREATED_AT,
  },
  {
    id: 9002,
    name: "Campus Graphic Tee",
    slug: "campus-graphic-tee",
    description: "A soft cotton tee with a minimal Sokoline-inspired print for daily wear.",
    price: "34.00",
    discount_price: null,
    is_on_sale: false,
    stock: 120,
    shop: 102,
    shop_name: "North Atelier",
    shop_slug: "north-atelier",
    category: { id: 2, name: "Apparel", slug: "apparel" },
    tags: [],
    images: [{ id: 3, image: "/about-section-image.jpg", alt_text: "Graphic tee", is_feature: true }],
    variants: [],
    shipping_info: "Ships in 2 business days.",
    return_policy: "Returns accepted within 14 days.",
    has_free_shipping: true,
    has_free_returns: false,
    is_safety_certified: true,
    average_rating: 4.4,
    review_count: 18,
    created_at: MOCK_CREATED_AT,
  },
  {
    id: 9003,
    name: "Desk Lamp Pro",
    slug: "desk-lamp-pro",
    description: "Adjustable LED desk lamp built for long study sessions and focused work.",
    price: "54.00",
    discount_price: "44.00",
    is_on_sale: true,
    stock: 64,
    shop: 103,
    shop_name: "Dorm Tech Lab",
    shop_slug: "dorm-tech-lab",
    category: { id: 3, name: "Tech", slug: "tech" },
    tags: [],
    images: [{ id: 4, image: "/hero-image.jpg", alt_text: "Desk lamp", is_feature: true }],
    variants: [],
    shipping_info: "Ships within 24 hours.",
    return_policy: "Returns accepted within 30 days.",
    has_free_shipping: false,
    has_free_returns: true,
    is_safety_certified: true,
    average_rating: 4.8,
    review_count: 52,
    created_at: MOCK_CREATED_AT,
  },
  {
    id: 9004,
    name: "Notebook Set",
    slug: "notebook-set",
    description: "Set of premium notebooks with ruled, dotted, and blank page options.",
    price: "24.00",
    discount_price: null,
    is_on_sale: false,
    stock: 210,
    shop: 104,
    shop_name: "Paper Foundry",
    shop_slug: "paper-foundry",
    category: { id: 4, name: "Stationery", slug: "stationery" },
    tags: [],
    images: [{ id: 5, image: "/about-section-image.jpg", alt_text: "Notebook set", is_feature: true }],
    variants: [],
    shipping_info: "Ships in 1–3 business days.",
    return_policy: "Returns accepted within 14 days.",
    has_free_shipping: false,
    has_free_returns: false,
    is_safety_certified: true,
    average_rating: 4.5,
    review_count: 12,
    created_at: MOCK_CREATED_AT,
  },
];
