# Generated by Django 6.0 on 2026-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_populate_product_slugs_and_enforce_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_free_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_safety_certified',
            field=models.BooleanField(default=False),
        ),
    ]
