"""
Django settings for sokoline project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

def get_env_robust(key, default=None):
    """Retrieves an env var and aggressively strips whitespace and quotes."""
    val = os.environ.get(key, default)
    if val:
        return val.strip().strip('"').strip("'")
    return val


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-development-key-change-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'sokoline-h9g7w.ondigitalocean.app',
    'sokoline.app',
    'www.sokoline.app',
    'api.sokoline.app',
    '*', 
] # Explicitly allow localhost and DO domain


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shops',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'storages',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'sokoline.authentication.ClerkAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# Clerk JWKS Endpoint from your dashboard
CLERK_JWKS_URL = os.environ.get('CLERK_JWKS_URL', "https://needed-wahoo-23.clerk.accounts.dev/.well-known/jwks.json")

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://www.sokoline.app",
    "https://sokoline.app",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = 'sokoline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sokoline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Toggle this to True in your .env to use SQLite locally
USE_LOCAL_DB = get_env_robust('USE_LOCAL_DB', 'False') == 'True'

if USE_LOCAL_DB:
    print("DEBUG: USE_LOCAL_DB is True, forcing SQLite")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    # 1. Try to build the configuration from individual variables (DigitalOcean GUI or .env)
    DB_HOST = get_env_robust('DB_HOST') or get_env_robust('DATABASE_HOST') or get_env_robust('host')
    DB_PORT = get_env_robust('DB_PORT') or get_env_robust('DATABASE_PORT') or get_env_robust('port')
    DB_NAME = get_env_robust('DB_DATABASE') or get_env_robust('DATABASE_NAME') or get_env_robust('database')
    DB_USER = get_env_robust('DB_USERNAME') or get_env_robust('DATABASE_USER') or get_env_robust('username')
    DB_PASS = get_env_robust('DB_PASSWORD') or get_env_robust('DATABASE_PASSWORD') or get_env_robust('password')

    if all([DB_HOST, DB_NAME, DB_USER, DB_PASS]):
        print(f"DEBUG: Using individual database credentials for host: {DB_HOST}")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': DB_NAME,
                'USER': DB_USER,
                'PASSWORD': DB_PASS,
                'HOST': DB_HOST,
                'PORT': DB_PORT or '25060',
                'OPTIONS': {
                    'sslmode': 'require',
                },
                'CONN_MAX_AGE': 600,
            }
        }
    else:
        # 2. Fallback: Try a single connection string
        raw_url = get_env_robust('DB_CONNECTION_STRING') or get_env_robust('DATABASE_URL') or ""
        
        # If it is a DO placeholder, empty, or missing a valid scheme, fall back to SQLite
        if not raw_url or "${" in raw_url or not raw_url.startswith(("postgres://", "postgresql://")):
            print("DEBUG: No valid PG connection found or malformed URL, falling back to SQLite")
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
                }
            }
        else:
            print(f"DEBUG: Using connection string (DATABASE_URL)")
            DATABASES = {
                'default': dj_database_url.parse(raw_url, conn_max_age=600)
            }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# DigitalOcean Spaces (CDN) Configuration
USE_SPACES = os.environ.get('USE_SPACES', 'False') == 'True'

if USE_SPACES:
    AWS_ACCESS_KEY_ID = os.environ.get('DO_SPACES_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = os.environ.get('DO_SPACES_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('DO_SPACES_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('DO_SPACES_ENDPOINT')
    AWS_S3_REGION_NAME = os.environ.get('DO_SPACES_REGION')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('DO_SPACES_CUSTOM_DOMAIN')
    
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# M-Pesa Daraja Settings
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE', '174379')
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', '')
MPESA_ENVIRONMENT = os.environ.get('MPESA_ENVIRONMENT', 'sandbox')
MPESA_CALLBACK_URL = os.environ.get('MPESA_CALLBACK_URL', 'https://sokoline.app/api/mpesa/callback/')

# Logging to capture errors in DigitalOcean logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
